-- liquibase formatted sql

-- changeset user:1730897093924-1
CREATE TABLE appointment
(
    appointment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status           VARCHAR(255),
    appointment_date TIMESTAMP WITHOUT TIME ZONE,
    client_id        BIGINT                                  NOT NULL,
    vehicle_id       BIGINT                                  NOT NULL,
    service_type     VARCHAR(255),
    schedule_id      BIGINT,
    CONSTRAINT pk_appointment PRIMARY KEY (appointment_id)
);

-- changeset user:1730897093924-2
CREATE TABLE auth_data
(
    auth_data_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password     VARCHAR(255),
    email        VARCHAR(255),
    role         VARCHAR(255),
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_auth_data PRIMARY KEY (auth_data_id)
);

-- changeset user:1730897093924-3
CREATE TABLE mechanic
(
    mechanic_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initials    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_mechanic PRIMARY KEY (mechanic_id)
);

-- changeset user:1730897093924-4
CREATE TABLE part_order
(
    part_order_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_name      VARCHAR(255),
    status         VARCHAR(255),
    appointment_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_part_order PRIMARY KEY (part_order_id)
);

-- changeset user:1730897093924-5
CREATE TABLE schedule
(
    schedule_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    manager_id     BIGINT                                  NOT NULL,
    appointment_id BIGINT,
    mechanic_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (schedule_id)
);

-- changeset user:1730897093924-6
CREATE TABLE "user"
(
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    patronymic   VARCHAR(255),
    phone_number VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

-- changeset user:1730897093924-7
CREATE TABLE vehicle
(
    vehicle_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    license_plate VARCHAR(255)                            NOT NULL,
    model         VARCHAR(255)                            NOT NULL,
    client_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_vehicle PRIMARY KEY (vehicle_id)
);

-- changeset user:1730897093924-8
ALTER TABLE appointment
    ADD CONSTRAINT uc_appointment_schedule UNIQUE (schedule_id);

-- changeset user:1730897093924-9
ALTER TABLE auth_data
    ADD CONSTRAINT uc_auth_data_email UNIQUE (email);

-- changeset user:1730897093924-10
ALTER TABLE auth_data
    ADD CONSTRAINT uc_auth_data_user UNIQUE (user_id);

-- changeset user:1730897093924-11
ALTER TABLE schedule
    ADD CONSTRAINT uc_schedule_appointment UNIQUE (appointment_id);

-- changeset user:1730897093924-12
ALTER TABLE vehicle
    ADD CONSTRAINT uc_vehicle_license_plate UNIQUE (license_plate);

-- changeset user:1730897093924-13
ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES "user" (user_id);

-- changeset user:1730897093924-14
ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id);

-- changeset user:1730897093924-15
ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicle (vehicle_id);

-- changeset user:1730897093924-16
ALTER TABLE auth_data
    ADD CONSTRAINT FK_AUTH_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (user_id);

-- changeset user:1730897093924-17
ALTER TABLE part_order
    ADD CONSTRAINT FK_PART_ORDER_ON_APPOINTMENT FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id);

-- changeset user:1730897093924-18
ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_APPOINTMENT FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id);

-- changeset user:1730897093924-19
ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES "user" (user_id);

-- changeset user:1730897093924-20
ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_MECHANIC FOREIGN KEY (mechanic_id) REFERENCES mechanic (mechanic_id);

-- changeset user:1730897093924-21
ALTER TABLE vehicle
    ADD CONSTRAINT FK_VEHICLE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES "user" (user_id);

